//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldenAnvil.Utility.Calendar {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OurResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OurResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoldenAnvil.Utility.Calendar.OurResources", typeof(OurResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} day.
        /// </summary>
        internal static string TimeOffsetDayLong_One {
            get {
                return ResourceManager.GetString("TimeOffsetDayLong_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} days.
        /// </summary>
        internal static string TimeOffsetDayLong_Other {
            get {
                return ResourceManager.GetString("TimeOffsetDayLong_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0}d.
        /// </summary>
        internal static string TimeOffsetDayShort_One {
            get {
                return ResourceManager.GetString("TimeOffsetDayShort_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0}d.
        /// </summary>
        internal static string TimeOffsetDayShort_Other {
            get {
                return ResourceManager.GetString("TimeOffsetDayShort_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} hour.
        /// </summary>
        internal static string TimeOffsetHourLong_One {
            get {
                return ResourceManager.GetString("TimeOffsetHourLong_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} hours.
        /// </summary>
        internal static string TimeOffsetHourLong_Other {
            get {
                return ResourceManager.GetString("TimeOffsetHourLong_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0}h.
        /// </summary>
        internal static string TimeOffsetHourShort_One {
            get {
                return ResourceManager.GetString("TimeOffsetHourShort_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0}h.
        /// </summary>
        internal static string TimeOffsetHourShort_Other {
            get {
                return ResourceManager.GetString("TimeOffsetHourShort_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} minute.
        /// </summary>
        internal static string TimeOffsetMinuteLong_One {
            get {
                return ResourceManager.GetString("TimeOffsetMinuteLong_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} minutes.
        /// </summary>
        internal static string TimeOffsetMinuteLong_Other {
            get {
                return ResourceManager.GetString("TimeOffsetMinuteLong_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0}m.
        /// </summary>
        internal static string TimeOffsetMinuteShort_One {
            get {
                return ResourceManager.GetString("TimeOffsetMinuteShort_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0}m.
        /// </summary>
        internal static string TimeOffsetMinuteShort_Other {
            get {
                return ResourceManager.GetString("TimeOffsetMinuteShort_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} month.
        /// </summary>
        internal static string TimeOffsetMonthLong_One {
            get {
                return ResourceManager.GetString("TimeOffsetMonthLong_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} months.
        /// </summary>
        internal static string TimeOffsetMonthLong_Other {
            get {
                return ResourceManager.GetString("TimeOffsetMonthLong_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0}M.
        /// </summary>
        internal static string TimeOffsetMonthShort_One {
            get {
                return ResourceManager.GetString("TimeOffsetMonthShort_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0}M.
        /// </summary>
        internal static string TimeOffsetMonthShort_Other {
            get {
                return ResourceManager.GetString("TimeOffsetMonthShort_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} second.
        /// </summary>
        internal static string TimeOffsetSecondLong_One {
            get {
                return ResourceManager.GetString("TimeOffsetSecondLong_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} seconds.
        /// </summary>
        internal static string TimeOffsetSecondLong_Other {
            get {
                return ResourceManager.GetString("TimeOffsetSecondLong_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0}s.
        /// </summary>
        internal static string TimeOffsetSecondShort_One {
            get {
                return ResourceManager.GetString("TimeOffsetSecondShort_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0}s.
        /// </summary>
        internal static string TimeOffsetSecondShort_Other {
            get {
                return ResourceManager.GetString("TimeOffsetSecondShort_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}.
        /// </summary>
        internal static string TimeOffsetTermJoin {
            get {
                return ResourceManager.GetString("TimeOffsetTermJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} year.
        /// </summary>
        internal static string TimeOffsetYearLong_One {
            get {
                return ResourceManager.GetString("TimeOffsetYearLong_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} years.
        /// </summary>
        internal static string TimeOffsetYearLong_Other {
            get {
                return ResourceManager.GetString("TimeOffsetYearLong_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0}y.
        /// </summary>
        internal static string TimeOffsetYearShort_One {
            get {
                return ResourceManager.GetString("TimeOffsetYearShort_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0}y.
        /// </summary>
        internal static string TimeOffsetYearShort_Other {
            get {
                return ResourceManager.GetString("TimeOffsetYearShort_Other", resourceCulture);
            }
        }
    }
}
